### ISSUE TITLE
Refresh Switch Entity

### ISSUE THREAD

**Issue by tayden-flitcroft** [bjhiltbrand/drone_mobile_home_assistant#27]
Firstly, it works great as is, I got it plugged into HA with ease, thank you. But is there any way to force a refresh of the car without interacting with the drone mobile application? When I configured this, it showed the location of my vehicle at a place I was at like 3 weeks ago (the last time I opened the app to remote start).

**Comment by bjhiltbrand** [comment]
You should be able to call the service "drone_mobile.refresh_device_status_[Vehicle Name With Spaces Replaced By Underscores]" in Home Assistant to trigger an update from the car as if you were opening the app. I usually call this before running any automations that I have set (like locking the doors at night) to ensure that they are in the status I expect them to be in. I kept this call separate from building it in to automations or status trackers, because there is a data limit for the API and I didn't want to get people blacklisted. ;) Also, this service call causes the drone mobile module in the car to wake up and use more power than it normally does, and I figured it would be best to allow a user to determine how fast they wanted to kill their car battery. :)

**Comment by bjhiltbrand** [comment]
That being said, I am not paying for the GPS functionality, so if there is an issue with it not working correctly, I will need to get API payloads from someone that is paying for that functionality so I can figure out what's up with the API call.

**Comment by itkfilelor** [comment]
> Owner

I am, and the location appears to be functioning properly for me.
